### ISSUE TITLE
Missing Newtonsoft JSON

### ISSUE THREAD

**Issue by Morgan-6Freedom** [scenario-labs/Scenario-Unity#100]
**Describe the bug**
When importing Scenario-Unity-0.2.3 in a blank Unity Project, I have an error 

**To Reproduce**
1. Create a Unity 2022.3.3 new 3D Core Project
2. Download Scenario 0.2.3 from the release page of this github
3. Extract Scenario folder into Assets folder

**Expected behavior**

**Screenshots**
![image](https://github.com/scenario-labs/Scenario-Unity/assets/49686866/d310b214-c2ad-4c87-906b-ea64f6da0297)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Fixed it by importing newtonsoft JSON :
> com.unity.nuget.newtonsoft-json

![image](https://github.com/scenario-labs/Scenario-Unity/assets/49686866/9840a196-be11-4470-aa9e-8132e5ea836d)

I think the solution is to update the documentation to explain people we should import this dependency first.

**Comment by mrbusysky** [comment]
I believe that version has install windows. 
You don't need to manually install dependencies.

**Comment by mrbusysky** [comment]
Yeah, we are on version 0.3.0 the install method will be changing. It's now a one click install file. It should be updated in a few days I am guessing once all the team is around. 0.2.3 was supposed to be a one click install file or if someone was updating from a previous version it was just drag and drop.

**Comment by Morgan-6Freedom** [comment]
What do you mean it's a one click install file ?
The procedure to install the plugin is still to drag & drop the repo inside a Unity Project :
![image](https://github.com/scenario-labs/Scenario-Unity/assets/49686866/89b55d9d-3f2b-460d-b31a-80a1973711e4)

Do we need to update the documentation ?

**Comment by Morgan-6Freedom** [comment]
To be closed it needs :
- The documentation has been updated
- The one click installer is available to download
