### ISSUE TITLE
Generated images not showing up.

### ISSUE THREAD

**Issue by mrbusysky** [scenario-labs/Scenario-Unity#144]
I have tried 5 times on Windows. When I try to generate images they are not showing up in images.
So I closed the images page and reloaded it then the images showed up after.
This issue only occurred after I hit the update button in the package manger.

So we may need to check this just in case for the FAQ

**Comment by Morgan-6Freedom** [comment]
can you record this issue ? (video) and tell me which version number you are using ?

**Comment by mrbusysky** [comment]
I found the condition in which this happens.

Step one open the images page, hit update or close unity, and restart it. Images will be open but there will be no images showing. If you try to generate like this as well it will stay glitched. Nothing will show up. Ill send you the video on slack.

**Comment by Fangh** [comment]
@TheLLspectre is working on a fix
