### ISSUE TITLE
Set up default dimension depending on model in Prompt Window

### ISSUE THREAD

**Issue by qvaleroo** [scenario-labs/Scenario-Unity#163]
If I select a model of type `sd-xl` `sd-xl-composition` or `sd-xl-lora` my default dimension should be between 1024 and 2048
Otherwise it is a `sd-1_5` or `sd-1_5-composition` or `sd-1_5-lora`  model and dimension should be 512 and 1024

**Comment by TheLLspectre** [comment]
What options I let @qvaleroo, currently we have this:


![Image](https://github.com/scenario-labs/Scenario-Unity/assets/30622829/941cd9e9-b772-43e1-8997-ed89d1736971)

Do I only let : `{1024,2048}` or more options `{1024, xxxx, xxxx, ..., 2048}`

**Comment by qvaleroo** [comment]
> What options I let @qvaleroo, currently we have this:
> 
> ![Image](https://private-user-images.githubusercontent.com/30622829/314132168-941cd9e9-b772-43e1-8997-ed89d1736971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NjM4NjMsIm5iZiI6MTcxMDg2MzU2MywicGF0aCI6Ii8zMDYyMjgyOS8zMTQxMzIxNjgtOTQxY2Q5ZTktYjc3Mi00M2UxLTg5OTctZWQ4OWQxNzM2OTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE1NTI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMjVjZTM4MTVkM2VhNzBlMzkzYTQwODZhZDU4M2VjOWFmNzBhOWNlZGVhOTAxN2EwODM3YjVhMmJkZDNmY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-fwJQuFin7eecprxs16JVQrJcRCHByqxA7S9DSRiZlw)
> 
> Do I only let : `{1024,2048}` or more options `{1024, xxxx, xxxx, ..., 2048}`

For SD1.5 you can let what you have.
For SDXL you can just do x2 on SD1.5 values
