### ISSUE TITLE
Complete Layer Editor

### ISSUE THREAD

**Issue by mrbusysky** [scenario-labs/Scenario-Unity#42]
Features
* Zoom in and out of canvas
* Panning
* Flip of image
* Cropping
* Rescale
* remove background
* leveling ui
* Dragging images in canvas
* Layer list
* set background
* and more

**Comment by Morgan-6Freedom** [comment]
#41 has been merged. What is the statut of this task @mrbusysky ?

**Comment by mrbusysky** [comment]
i switch the method of the layer editor: https://github.com/scenario-labs/Scenario-Unity/issues/178
