### ISSUE TITLE
Code error when opening Scenario on Unity2022.3.4

### ISSUE THREAD

**Issue by XHflame** [scenario-labs/Scenario-Unity#71]
**Describe the bug**
When I leave https://github.com/scenario-labs/Scenario-Unity/releases/download/v0.1.1/Scenario3D.zip

After downloading the file, I encountered a code error in the Assets section where I placed Scenario in Unity. The specific code error is as follows: Assets Scenario Plugins ApiClient. cs (1,7): error CS0246: The type or namespace name 'Cytoharp' could not be found (are you missing a using directive or an assembly reference?)

Assets Scenario Plugins ApiClient.cs (13,25): error CS0246: The type or namespace name 'UniTask<>' could not be found (are you missing a using directive or an assembly reference?)

Assets Scenario Plugins ApiClient.cs (37,25): error CS0246: The type or namespace name 'UniTask<>' could not be found (are you missing a using directive or an assembly reference?)

**To Reproduce**

**Expected behavior**
Unity can operate normally
If someone can help me answer, you can leave a message below or email me 1906875738@qq.com
**Screenshots**
![c457fbdf132406c99bbfd648515c37d](https://github.com/scenario-labs/Scenario-Unity/assets/41466816/4e92fefe-170b-4d28-9f31-179fa30023b5)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mrbusysky** [comment]
Have you followed all the steps?
Delete the JSON files and reinstall unitask in first install file.

**Comment by XHflame** [comment]
After I imported the files from Scenario into Unity, there were no other operations and a bug appeared. Can you share the Unity project you used? thanks

**Comment by mrbusysky** [comment]
You imported all the files? You are only supposed to put the install file in one by one as per the install guide. Delete every file other than install file  1 then when done with that add install file 2 once that is done then you can add the other files. You can find the install guide in the readme

**Comment by XHflame** [comment]
I will https://github.com/scenario-labs/Scenario-Unity/releases/download/v0.1.1/Scenario3D.zip The above error occurred when importing into the Unity3D project

**Comment by mrbusysky** [comment]
That error that is occurring is from one of the dependencies not being installed. 

Are you on mac or windows?

**Comment by XHflame** [comment]
windows

**Comment by mrbusysky** [comment]
Then I would recommend removing all files related to scenario and following the guide step by step.

If this doesn't work you will need to manually add the package. But as a window users it should work just fine following the guide as the steps say. If this does not work I'll send how to manually install the package

**Comment by XHflame** [comment]
Sorry, I may not have enough abilities to solve this problem, but I really want to experience the power of scenario in Unity. Can you share the project with me? Thank you for helping me solve the problem. Thank you

**Comment by mrbusysky** [comment]
for unitask: go to window > package manager > hit the + > add package from github url > https://github.com/Cysharp/UniTask.git?path=src/UniTask/Assets/Plugins/UniTask#2.1.0

**Comment by XHflame** [comment]
With your help, I followed the method you suggested. My project no longer had the previous bug, and then this error occurred. Assets Scenario Editor Images Images.cs (12,7): error CS0246: The type or namespace name 'RestSharp' could not be found (are you missing a using directive or an assembly reference?). Can I comment out the code related to RestSharp directly? Will this affect the functionality of Scenario?

**Comment by mrbusysky** [comment]
Did you do the second install file as well?

**Comment by mrbusysky** [comment]
You can find it after it is installed in window
