### ISSUE TITLE
On mac, buttons are out of the screen and without colors

### ISSUE THREAD

**Issue by qvaleroo** [scenario-labs/Scenario-Unity#89]
On image editor window, buttons are going out of the screen (13 inches) and there is no color

<img width="1440" alt="image" src="https://github.com/scenario-labs/Scenario-Unity/assets/95273550/7af6e3c0-c9b3-40ca-8ebd-46bb1722e4d2">

**Comment by Morgan-6Freedom** [comment]
On MacOS, Retina displays does not give the correct resolution to Unity.
https://stackoverflow.com/questions/51667845/getting-retina-screen-resolution-on-macs-with-hidpi-in-unity

I'm trying to find a fix
